### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by olafleur** [ArcBees/poker-planning#21]
Nice to see some Dart running at ArcBees! @dzenanr will be happy! ;-)

However, the build is currently failing. :-(

**Comment by Pacane** [comment]
Yep. We have a long branch running fixing multiple things :P

**Comment by dzenanr** [comment]
Glad to hear that Dart is used in Quebec.

**Comment by Pacane** [comment]
Hi @dzenanr, I've learned Dart with your book! :)
